### ISSUE TITLE
U-Boot is used as a binary, build in OE isn't bootable

### ISSUE THREAD

**Issue by stoupa-cz** [stoupa-cz/meta-odroid#2]
Currently a prebuilt binary of u-boot.bin is used. With soft float DEFAULTTUNE (cortexa5-neon) the u-boot is buildable, but boot fails like this:

```
Loading U-boot...success.

U-boot-00000-gf631c80-dirty(odroidc@f631c809) (Mar 17 2015 - 15:15:38)

DRAM:  1 GiB
relocation Offset is: 2ff1c000
MMC:   SDCARD: 0, eMMC: 1
Enter Exception:0x00000001
    link addr:0x3ff67684
```

With hard float DEFAULTTUNE (cortexa5hf-neon) the u-boot is not buildable. Instructions at https://code.google.com/p/chromium/issues/detail?id=213120 helps\* to build, but the exception remains

\* Well, you need to update line to:

```
PLATFORM_CPPFLAGS += $(call cc-option,-mcpu=cortex-a5 -ffixed-r8 -mno-long-calls  -Wall -fPIC -mfloat-abi=hard -mfpu=vfpv3 )
```

in

```
arch/arm/cpu/aml_meson/config.mk
```

**Comment by wetekenigma** [comment]
You may have a look at [this](https://github.com/endlessm/u-boot-meson/commits/master) repository they did a lot of compatibility fixes for **cross_compilation**. The commit [b208e7c...](https://github.com/endlessm/u-boot-meson/commit/b208e7c0789fee2efacaaa33e077cb07881dd1c0) May fixes this trouble...

**Comment by stoupa-cz** [comment]
Thanks for a pointer, I will try later. I was thinking that build with be ok, but OE's internal compiler is somehow different.

**Comment by stoupa-cz** [comment]
So commit b208e7c didn't help :(... I was also checking if there is -mno-unaligned-access and this is also present. But comparing the endelssm/u-boot-meson I have different way to cross-compile for hf, so I will also test this later when time permits.

**Comment by graugans** [comment]
I've fixed the u-boot trouble for hardfp in my [forked repo](https://github.com/graugans/u-boot/tree/odroidc-v2011.03-armhf). Now u-boot just boots fine :)

```
-----------------------------------------------------------------------
* Welcome to Hardkernel's ODROID-C... (Built at 19:33:00 Dec  8 2014) *
-----------------------------------------------------------------------
CPU : AMLogic S805
MEM : 1024MB (DDR3@792MHz)
BID : HKC13C0001
S/N : HKC1CC037EB6A2AE
0x0000009f
check SD_boot_type:0x1   card_type:0x1
Loading U-boot...success.


U-boot-00000-ge1789eb-dirty(odroidc@odroidc-v2011.03) (Mar 28 2015 - 21:28:27)

DRAM:  1 GiB
relocation Offset is: 2ff1c000
MMC:   SDCARD: 0, eMMC: 1
IR init is done!
vpu clk_level = 3
set vpu clk: 182150000Hz, readback: 182150000Hz(0x701)
mode = 6  vic = 4
set HDMI vic: 4
mode is: 6
viu chan = 1
config HPLL
config HPLL done
reconfig packet setting done
MMC read: dev # 0, block # 33984, count 12288 ... 12288 blocks read: OK
There is no valid bmp file at the given address
============================================================
Vendor: Man 035344 Snr 292e6d0e Rev: 8.0 Prod: SU08G
            Type: Removable Hard Disk
            Capacity: 7580.0 MB = 7.4 GB (15523840 x 512)
------------------------------------------------------------
Partition     Start Sector     Num Sectors     Type
    1                 3072          263168       6
    2               266240         9336832      83
============================================================
Net:   Meson_Ethernet
init suspend firmware done. (ret:0)
Hit Enter key to stop autoboot -- :  1 tstc enter

exit abortboot: 1
odroidc#
odroidc#
odroidc#
```

**Comment by stoupa-cz** [comment]
Perfect! I will add the lldiv() patch to the OE (along with the hf build fix). Thanks for sharing.

**Comment by stoupa-cz** [comment]
So graugans already provided the pull request with all necessary parts. I tested it on my C1 and it works.
