### ISSUE TITLE
Please support current master branch

### ISSUE THREAD

**Issue by rzr** [stoupa-cz/meta-odroid#5]
Uboot recipe for odroid-xu4 should be updated

**Comment by stoupa-cz** [comment]
Hi, this was a fork just to support some stuff and merge it back. Please use a meta layer which is maintained.

**Comment by rzr** [comment]
yes I asked at: https://github.com/siretart/meta-odroid/pull/1

**Comment by stoupa-cz** [comment]
BTW @rzr , you may find some info on the README of this project.

**Comment by rzr** [comment]
yes I've seen "CURRENT STATUS: This layer is not actively maintained anymore. "

So I suggested that  community could co-maintain it in @abandonware's meta-odroid org see

https://rzr.github.io/rzr-presentations/docs/abandonware#:2021:

Feel free to open PR if you want to merge your changes in:

https://github.com/abandonware/meta-odroid

Relate-to: https://github.com/abandonware/meta-odroid/issues/2

**Comment by stoupa-cz** [comment]
@rzr I briefly checked other repos and https://github.com/akuster/meta-odroid looks like the maintained layer based on my repo. I listed it also in my README few years ago. It is also listed on layers.openembedded.org. There is also meta-meson https://github.com/superna9999/meta-meson , which is also listed on the layers.openembedded.org and it seems like maintained. The abandonware/meta-odroid is 8 years old repo (but I must admit that I didn't check the presentation you've posted).

**Comment by rzr** [comment]
yes I know about meson, I even have patches in but I am interested into xu4 support only C1+ +N2 are listed in:
https://github.com/superna9999/meta-meson/tree/dunfell/conf/machine

Relate-to: https://github.com/adoptware/pinball/issues/7
